FILES= "azrael.gsl" "dukebeary.gsl" "gamewon_1p.gsl" "herbert.gsl" "interlevel.gsl" "levels.gsl" "libface.gsl" "mcflurry.gsl" "mechapuyo.gsl" "megapuyo.gsl" "monk.gsl" "orloff.gsl" "story1.gsl" "story2.gsl" "story3.gsl" "story4.gsl" "story5.gsl" "story6.gsl" "story7.gsl" "story8.gsl" "story9.gsl" "zklogh.gsl"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
