FILES= "interlevel.gsl" "levels.gsl" "story1.gsl" "story2.gsl" "story3.gsl" "story4.gsl" "story5.gsl" "story6.gsl" "story7.gsl" "story8.gsl" "story9.gsl"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
