FILES="opponentz.gsl" "gamelost1p.gsl" "title_fg.gsl" "networkmenu.gsl" "gameover1p.gsl" "gamelost2p_left.gsl" "title_bg.gsl" "flying_flobo.gsl" "storyz.gsl" "gamelost2p_right.gsl" "flying_saucer.gsl" "gamewon_1p.gsl" "gamewon_highscores_1p.gsl"

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
