FILES="gamelost1p.gsl" "opponentz.gsl" "title_fg.gsl" "networkmenu.gsl" "gameover1p.gsl" "gamelost2p_left.gsl" "title_bg.gsl" "flying_flobo.gsl" "gamelost2p_right.gsl" "storyz.gsl" "flying_saucer.gsl" 

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
