FILES= puyo-b-frame1.png puyo-b-frame2.png puyo-g-frame1.png puyo-g-frame2.png\
       puyo-r-frame1.png puyo-r-frame2.png puyo-v-frame1.png puyo-v-frame2.png\
       puyo-y-frame1.png puyo-y-frame2.png

include ${SOURCE_DATADIR}/Datarules.mk
