FILES= "bluestar.png" "chatzonebg.png" "cursor.png" "flash.png" "flash25.png" "flash50.png" "flash75.png" "font.ttf" "font3b.png" "font4b.png" "fontdark.png" "greenstar.png" "hall-of-fame.png" "happypuyo.png" "intro-main.jpg" "knockedpuyo.png" "laser.png" "menubg-wide.png" "menubg.png" "null.png" "redstar.png" "saucer.png"
DIRECTORIES= "balloon" "city" "etherdown" "kaori_gamelost" "kaori_title" "title" "unmappedmonster"
include ${SOURCE_DATADIR}/Datarules.mk
