FILES="font4b.png" "happypuyo.png" "menubg-wide.png" "redstar.png" "laser.png" "fontdark.png" "intro-main.jpg" "null.png" "menubg.png" "bluestar.png" "saucer.png" "chatzonebg.png" "hall-of-fame.png" "greenstar.png" "knockedpuyo.png" "font3b.png" 

DIRECTORIES="unmappedmonster" "title" "kaori_gamelost" "kaori_title" "city" 

include ${SOURCE_DATADIR}/Datarules.mk
