FILES="font4b.png" "happypuyo.png" "menubg-wide.png" "redstar.png" "fontdark.png" "null.png" "menubg.png" "bluestar.png" "greenstar.png" "knockedpuyo.png" "font3b.png"  "chatzonebg.png" "hall-of-fame.png"

DIRECTORIES="unmappedmonster" "title" "kaori_gamelost" "kaori_title" "city" 

include ${SOURCE_DATADIR}/Datarules.mk
