textnetcenter: TextNetCenter.cpp ../PuyoNetGameCenter.cpp ../PuyoInternetGameCenter.cpp
	g++ -g -o textNetCenter TextNetCenter.cpp ../PuyoNetGameCenter.cpp ../PuyoInternetGameCenter.cpp -I.. -I../iosfc -L../iosfc -liosfc -lcurses
