FILES= "Description.gsl" "farm-background.jpg" "forest-background.jpg" "landfill-background.jpg" "mansion-background-grid.png" "mansion-background.jpg"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
