FILES=

DIRECTORIES="background" "herbert_close" "kaori_farther" "balloon" "introherbert" "puyo_farther" "kaori_close" "herbert" "kaori_far" "introorloff" "orloff"

include ${SOURCE_DATADIR}/Datarules.mk
