FILES=

DIRECTORIES="background" "herbert_close" "kaori_farther" "introorloff" "balloon" "introherbert" "puyo_farther" "orloff" "kaori_close" "herbert" "kaori_far" 

include ${SOURCE_DATADIR}/Datarules.mk
