FILES=
DIRECTORIES= "background" "balloon" "herbert" "herbert_close" "introherbert" "introorloff" "kaori_close" "kaori_far" "kaori_farther" "orloff" "puyo_farther"
include ${SOURCE_DATADIR}/Datarules.mk
