#!/bin/sh

SELFCALL="$0"
if [ $# -eq 0 ]; then
  FPDATA='$(datadir)/flobopuyo'
  OUTPUTFILE=Makefile.am
else
  FPDATA="$2"
  OUTPUTFILE="$1"
fi

generate_makefile_am()
{
  OUTFILE="$1"
  DESTDIR="$2"
  DIRNAME=$(basename `pwd`)
  FILELIST=""
  DIRLIST=""
  while read LINE; do
    if [ -d $LINE ]; then
      CURDIR=`basename "$LINE"`
      DIRLIST="$DIRLIST $CURDIR"
    else
      FILELIST="$FILELIST $LINE"
    fi
  done <<EOF
    $(svn ls -r HEAD | grep -v Makefile | grep -v .mk | grep -v .sh)
EOF
  echo "# Autogenerated with create_automake.sh" > ${OUTFILE}
#  echo "${DIRNAME}dir = ${DESTDIR}" >> ${OUTFILE}
#  echo "dist_${DIRNAME}_DATA = ${FILELIST}" >> ${OUTFILE}
  echo "fpdatadir = ${DESTDIR}" >> ${OUTFILE}
  echo "dist_fpdata_DATA = ${FILELIST}" >> ${OUTFILE}
  echo "SUBDIRS = ${DIRLIST}" >> ${OUTFILE}
  echo >> ${OUTFILE}

  for CURDIR in $DIRLIST; do
    echo "Recursing in $DESTDIR/$CURDIR"
    cd "$CURDIR"
    "../$SELFCALL" "$OUTFILE" "$DESTDIR/$CURDIR"
    cd ..
  done
}

generate_makefile_am "$OUTPUTFILE" "$FPDATA"
