FILES= "bg_intro3.jpg" "cendres1.png" "cendres2.png" "dog.png" "grandma-frame1-small.png" "grandma-frame2-small.png" "halo_frame1.png" "halo_frame2.png" "laser.png" "saucer.png"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
