FILES="halo_frame1.png" "halo_frame2.png" "bg_intro3.jpg" "saucer.png" "cendres1.png" "cendres2.png" "laser.png" "grandma-frame1-small.png" "dog.png" "grandma-frame2-small.png" 

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
