FILES=flobopuyo_gameover.xm strange_fear2.xm flobopuyo_game1.xm \
      flobopuyo_menu.xm strange_gameover.xm flobopuyo_game2.xm \
      strange_fear.xm

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
