FILES= "flobopuyo_game1.xm" "flobopuyo_game2.xm" "flobopuyo_gameover.xm" "flobopuyo_menu.xm" "strange_fear2.xm" "strange_fear.xm" "strange_gameover.xm" "waitnrelax.xm"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
