FILES="strange_fear.xm" "flobopuyo_menu.xm" "strange_fear2.xm" "flobopuyo_gameover.xm" "flobopuyo_game1.xm" "strange_gameover.xm" "flobopuyo_game2.xm" "waitnrelax.xm"

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
