FILES= "applose.wav" "bam1.wav" "bim1.wav" "bim2.wav" "ebenon.wav" "fff.wav" "pastaga.wav" "pop.wav" "remove.wav" "slide.wav" "splash1.wav" "splash2.wav" "splash3.wav" "splash4.wav" "splash5.wav" "splash6.wav" "splash7.wav" "splash8.wav" "whip.wav" "whop.wav" "woho.wav" "woo.wav" "yahoohoo.wav"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
