FILES="skynight.jpg" "kaori-mini.png" "shadow-mini.png" "peak.png" "orloff-mini.png" "herbert-mini.png" "unmapped-mini.png" "dukebeary-mini.png" "azrael-mini.png"

DIRECTORIES=

include ${SOURCE_DATADIR}/Datarules.mk
