FILES= "azrael-mini.png" "dukebeary-mini.png" "frankenpuyo-mini.png" "herbert-mini.png" "kaori-mini.png" "mcflurry-mini.png" "orloff-mini.png" "peak.png" "shadow-mini.png" "skynight.jpg" "unmapped-mini.png"
DIRECTORIES=
include ${SOURCE_DATADIR}/Datarules.mk
